function [fitresult, gof] = createFitADCCalib(Voltage, Weight,Name)
%CREATEFIT(VOLTAGE,WEIGHT)
%  Create a fit.
%
%  Data for 'Amp5' fit:
%      X Input : Voltage
%      Y Output: Weight
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Oct-2017 17:36:46


%% Fit: 'Amp5'.
[xData, yData] = prepareCurveData( Voltage, Weight );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', Name );
h = plot( fitresult, xData, yData );
legend( h, 'Weight vs. Voltage', Name, 'Location', 'NorthEast' );
% Label axes
xlabel('Voltage [V]');
ylabel('Weight [N]');
title(sprintf('y=%.2f x %.2f',fitresult.p1,fitresult.p2));
grid on


